name: loggerx
description: Tiny but powerful logger with default root logger and ability to create custom loggers with runtime level filtering.
version: 2.0.0
homepage: https://abobija.com
repository: https://github.com/abobija/loggerx

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.19.0
dev_dependencies:
  lints: ^3.0.0
