name: loggerx
description: Tiny but powerful console logger with default root logger and ability to create custom loggers with runtime level filtering.
version: 1.0.0
homepage: https://abobija.com
repository: https://github.com/abobija/loggerx

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies: 
  intl: ^0.17.0
